vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.o.autoindent = true
vim.o.autoread = true
vim.o.background = "dark"
vim.o.backspace = "indent,eol,start"
vim.opt.clipboard:append("unnamedplus")
vim.o.completeopt = "menu,menuone,noselect"
vim.o.confirm = true
vim.o.copyindent = true
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.grepformat = "%f:%l:%c:%m"
vim.o.grepprg = "rg --vimgrep"
vim.o.ignorecase = true
vim.o.laststatus = 3
vim.o.mouse = "a"
vim.o.number = true
vim.o.pumblend = 10
vim.o.pumheight = 10
vim.o.relativenumber = true
vim.o.scrolloff = 10
vim.o.shiftround = true
vim.o.shiftwidth = 2
vim.o.shortmess = "ltToOcCFW"
vim.o.showmode = false
vim.o.signcolumn = "yes"
vim.o.smartcase = true
vim.o.splitbelow = true
vim.o.splitkeep = "screen"
vim.o.splitright = true
vim.o.tabstop = 2
vim.o.termguicolors = true
vim.o.timeoutlen = 300
vim.o.wildmode = "longest:full,full"
vim.o.wrap = false
vim.o.hlsearch = true
vim.o.swapfile = false
